# Generated by Django 2.2.5 on 2020-09-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='if_active',
            new_name='is_active',
        ),
    ]
